hardcodedNameSpace: checkov
showVerionsTab: false
showEnvVarsTab: false
allowAutoApplyLimits: false
name: Checkov
title: Checkov
logo: BellOutlined
tags:
  - Security
  - Checkov
description: Checkov https://www.checkov.io/4.Integrations/Kubernetes.html
oneDeploymentPerCluster: true
notAllowRemoveNamespace: true
autoAddEnvVarsToDeployments: false
